### PR TITLE
better kernel with f2fs fixes

### PR DESCRIPTION
**Pull request by erfanoabdi**
now superSU systemless and new magisk working

### CODE REVIEW

**Review by Vachounet — COMMENTED** [review]
Don't get it. What's the point of this ?

Prebuilt kernel ???

What does "better kernel" means ?

We don't have any root issue with current sources. (systemless or not)

Edit: NVM, didn't notice this is for pac :)

**Comment by Shr3ps** [comment]
+1 Vachounet, what's the relation between the kernel used by TWRP and SuperSU ?

**Comment by erfanoabdi** [comment]
I just patched this on kernel for SuperSU systemless
https://forum.xda-developers.com/showpost.php?p=70492947&postcount=8793

**Comment by Shr3ps** [comment]
Thanks for the link detail, I just made the relation with the XDA post ^^
Vachounet has already backported an uptodate F2FS driver into the kernel, so I think those modifications are not relevant anymore. But we can backport thoses patches if needed.
Did you try to flash SuperSU with my TWRP build ?

**Comment by erfanoabdi** [comment]
No sorry I didn't try your build, that's why I closed pull, sorry :p 
But first because of old phh's superuser you have linked in your XDA thread I thought f2fs is old one like official TWRP

**Pull request closed without merging**
