### PR TITLE
griffin: Enable tethering in build prop

### PR DESCRIPTION
**Pull request by JooJooBee666**
Change-Id: Ib0d7a7556dd22f0e08c0fc8e05218e40615dbfc3

### CODE REVIEW

**Comment by Vachounet** [comment]
Hi,

Are you sure this is really needed ? WiFi tethering seems to work fine without this.
Could you give more details ?

**Comment by JooJooBee666** [comment]
Sure.  The option to tether is disabled for me if I don't have that added in.  Maybe it's an AT&T thing?

**Comment by Vachounet** [comment]
That's possible, the option is not disable for me. Dunno what to do with this.

**Comment by stargo** [comment]
I think the problem is actually that the carrier configs in overlay/ specify a tethering entitlement app for some carriers, but the app is not shipped at all:

Example for one of the AT&T MCC MNC pairs (310 150):

https://github.com/boulzordev/android_device_motorola_griffin/blob/cm-14.1/overlay/frameworks/base/core/res/res/values-mcc310-mnc150/arrays.xml#L3

https://github.com/boulzordev/android_device_motorola_griffin/blob/cm-14.1/overlay/frameworks/base/core/res/res/values-mcc310-mnc150/strings.xml#L3

I think the best solution would be to just get rid of everything related to config_mobile_hotspot_provision in the overlays.

**Comment by JooJooBee666** [comment]
ok, this has been cleaned up and verified working using stargo's suggestion.

**Comment by Vachounet** [comment]
Well done guys ;)

**Pull request merged**
